version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgresql://tani:tani@db/email_db
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: tani
      POSTGRES_PASSWORD: tani
      POSTGRES_DB: email_db
    ports:
      - "5432:5432"

  worker:
    build: .
    command: celery -A main.celery worker --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgresql://tani:tani@db/email_db
      - REDIS_URL=redis://redis:6379/0
